<?php

namespace TwelveCode\MShell;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-20 at 10:06:13.
 */
class CommandFactoryTest extends \PHPUnit_Framework_TestCase
{


    /**
     * @covers TwelveCode\MShell\CommandFactory::getCommand
     */

    public function testGetCommandExisting()
    {
        $cmd = CommandFactory::getCommand(2, array('run.php', 'help'));

        $this->assertInstanceOf('TwelveCode\MShell\ACommand', $cmd);
        $this->assertInstanceOf('TwelveCode\MShell\Command\Help', $cmd);
    }

    /**
     * @covers TwelveCode\MShell\CommandFactory::getCommand
     * @expectedException TwelveCode\MShell\Exception\CommandNotFound
     */

    public function testGetCommandNotExisting()
    {
        $cmd = CommandFactory::getCommand(2, array('run.php', 'fooBarBaz'));
    }

    /**
     * @covers TwelveCode\MShell\CommandFactory::getCommand
     * @expectedException TwelveCode\MShell\Exception\CommandNotSpecified
     */

    public function testGetCommandNotSpecified()
    {
        $cmd = CommandFactory::getCommand(1, array('run.php'));
    }
}
